/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_hd_internal_Scan.h"
#include <ls300/hd_laser_scan.h>
/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_create
 * Signature: (J)I
 */
JNIEXPORT jlong JNICALL Java_com_hd_internal_Scan_sj_1create__J
(JNIEnv *env, jclass clazz) {
	int ret;
	struct scan_job_t* ptr;
	ret = sj_create(&ptr);
	e_assert(ret>0, 0);
	return (jlong) ptr;
}

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_create
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_hd_internal_Scan_sj_1create__JLjava_lang_String_2I
(JNIEnv *env, jclass clazz, jlong priv, jstring str, jint port) {
	int ret;
	char *ip;
	struct scan_job_t* ptr;
	ip = (*env)->GetStringUTFChars(env, str, 0);
	ret = sj_create_ex(&ptr, (laser_control_t*)priv,ip, port);
	(*env)->ReleaseStringUTFChars(env, str, ip);
	e_assert(ret>0, 0);
	return (jlong) ptr;
}

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Scan_sj_1destroy
(JNIEnv *env, jclass clazz, jlong priv) {

	int ret;
	struct scan_job_t* scan = (struct scan_job_t*) priv;
	e_assert(scan!=NULL, 0);
	ret = sj_destroy(scan);
	e_assert(ret>0, 0);
	return 1;
}

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Scan_sj_1start
(JNIEnv *env, jclass clazz, jlong priv) {
	int ret;
	struct scan_job_t* scan = (struct scan_job_t*) priv;
	DMSG((STDOUT,"TRY START SCAN."));
	e_assert(scan!=NULL, 0);
	ret = sj_start(scan);
	e_assert(ret>0, 0);
	DMSG((STDOUT,"START SCAN SUCCESS."));
	return 1;
}

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Scan_sj_1stop
(JNIEnv *env, jclass clazz, jlong priv) {
	int ret;
	struct scan_job_t* scan = (struct scan_job_t*) priv;
	e_assert(scan!=NULL, 0);
	ret = sj_stop(scan);
	e_assert(ret>0, 0);
	return 1;
}

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_wait
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Scan_sj_1wait
(JNIEnv *env, jclass clazz, jlong priv) {
	int ret;
	struct scan_job_t* scan = (struct scan_job_t*) priv;
	DMSG((STDOUT,"TRY WAIT SCAN."));
	e_assert(scan!=NULL, 0);
	ret = sj_wait(scan);
	DMSG((STDOUT,"SCAN DONE."));
	e_assert(ret>0, 0);
	return 1;
}

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_config
 * Signature: (JIDDIDDD)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Scan_sj_1config
(JNIEnv *env, jclass clazz, jlong priv, jint p1, jdouble p2, jdouble p3, jint p4,
		jdouble p5, jdouble p6, jdouble p7) {
	int ret;
	struct scan_job_t* scan = (struct scan_job_t*) priv;
	e_assert(scan!=NULL, 0);
	ret = sj_config(scan, p1, p2, p3, p4, p5, p6, p7);
	e_assert(ret>0, 0);
	return 1;
}

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_set_data_dir
 * Signature: (JLjava/lang/String{}Ljava/lang/String{})I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Scan_sj_1set_1data_1dir
(JNIEnv *env, jclass clazz, jlong priv, jstring str, jstring str1) {
	int ret;
	char *dir,*dir1;
	struct scan_job_t* scan = (struct scan_job_t*) priv;
	e_assert(scan!=NULL, 0);
	dir = (*env)->GetStringUTFChars(env, str, 0);
	dir1 = (*env)->GetStringUTFChars(env, str1, 0);
	ret = sj_set_data_dir(scan, dir,dir1);
	(*env)->ReleaseStringUTFChars(env, str, dir);
	(*env)->ReleaseStringUTFChars(env, str1, dir1);
	e_assert(ret>0, 0);
	return 1;
}
