/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hd_internal_Scan */

#ifndef _Included_com_hd_internal_Scan
#define _Included_com_hd_internal_Scan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_hd_internal_Scan_sj_1create__
  (JNIEnv *, jclass);

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_create
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_hd_internal_Scan_sj_1create__JLjava_lang_String_2I
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Scan_sj_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Scan_sj_1start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Scan_sj_1stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_wait
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Scan_sj_1wait
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_config
 * Signature: (JIDDIDDD)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Scan_sj_1config
  (JNIEnv *, jclass, jlong, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

/*
 * Class:     com_hd_internal_Scan
 * Method:    sj_set_data_dir
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hd_internal_Scan_sj_1set_1data_1dir
  (JNIEnv *, jclass, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
