/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hd_scan_SickLD */

#ifndef _Included_com_hd_scan_SickLD
#define _Included_com_hd_scan_SickLD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hd_scan_SickLD
 * Method:    main
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hd_scan_SickLD_main
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
